# These are supported funding model platforms
# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [nicholascarey]
#patron: # Replace with a single Patron username
#open_collective: # Replace with a single Open Collective username
#ko fi: # Replace with a single Ko-fi username
#tidelift: # Replace with a single Tidelift platform-name/package-name e.g., pm/babel
#community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
#liberapay: # Replace with a single Liberapay username
#issuehunt: # Replace with a single IssueHunt username
#techie: # Replace with a single Otechie username
#custom: # Replace with up to 4 custom sponsorship URLs e.g., ('linkl', "link2'1

github: [nicholascarey]
custom: ["https://www.paypal.me/njcarey", "https://settleup.starlingbank.com/nicholascarey"]
