---
title: Contact
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 3
resource_files:
vignette: >
  %\VignetteIndexEntry{Contact}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Developers

`respR` is designed, programmed, and maintained by [**Januar Harianto**](https://github.com/januarharianto) and [**Nicholas Carey**](https://github.com/nicholascarey). We are biologists and created `respR` to assist with our own work, before realising it would be useful to the scientific community. We have done this almost entirely in our spare time, spending many hundreds of hours working on the package. 

## Contact

If you have any feedback about using `respR` feel free to get in touch: 

- General questions or trouble getting started - contact via [**email**](mailto:nicholascarey@gmail.com)

- Bugs, problems, or feature requests - open a [**Github Issue**](https://github.com/januarharianto/respR/issues)

- Want to dive into the code and fix it? - fork the [**Github repo**](https://github.com/januarharianto/respR/) and do a [**Pull Request**](https://github.com/januarharianto/respR/pulls)

## Twitter

`respR` has a [Twitter account](https://twitter.com/respR_pkg). Follow for the latest news and updates. 


## Slack and Discord

We have set up a Discord channel to discuss respR. Go [here](https://discord.gg/JKkarCTW4N) to request an invite. 

Alternatively, join our open Slack workspace [here](https://join.slack.com/t/respr-open/shared_invite/zt-13gttchaf-eCxIlifhDr_Q7GbtMzYgxQ). 

We are at present just trying these out. Which of them we will use going forward will depend on how many people use them. It is likely that we may abandon one or both if there isn't much interest or utility! 

## Support

`respR` is free to use and always will be. We have spent literally hundreds of hours developing the package, writing code and documentation, and even on one-to-one help getting users started with their analyses. This help will always be available, you just need to [**ask**](mailto:nicholascarey@gmail.com). 

If 

Github sponsor?
