---
title: respR v2 - Code changes
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{respR v2 - Code changes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

`respr v2.0` was a huge rewrite and rethinking of the entire package. During this process it quickly became clear we could not update the package satisfactorily without breaking some code from v1.x. Therefore, we took the decision to implement these and other improvements in the belief that it was better to do it now and have the package work consistently and logically well into the future. 

While the majority of the package workflows are in general unchanged, and older code *may* work, but there are enough changes that we recommend old code not be used with v2. `respR` workflows are generally concise and overall work in the same way, so updating code to be compatible should be relatively straightforward. 

This is an *incomplete* summary of the major code changes in v2.0, with some suggestions for how to update older code to allow it to work.  See [here]() for full version notes for this release. 

IF you have completed or are in the process of submitting a publication and `respR v1.x` code as supplementary information, see [here]() for information about how to include a link to `respR v1.1` so that this code will be reproducible in the future. 

If you come across any changes that are not documented here, [**let us know**](mailto:nicholascarey@gmail.com) and we will add it to the list. 

### Deprecated functions

`inspect_data` and `pcrit` were officially deprecated some time ago, and have been completely removed in this version. Update code to use `inspect()` and `oxy_crit()` instead.

### Pcrit analyses

As well as `pcrit` being removed, `calc_prit` has been renamed `oxy_crit()` to avoid conflicts with another package. 

### Flowthrough respirometry analyses

The entire workflow for analysing flowthrough respirometry data has changed. Any previous code for analysing these types of data will likely not work, and should be rewritten using the four new specialised functions. See `vignette("flowthrough")` for more details.

### Input changes

Several function inputs have been renamed to make them more consistent. 

 - All primary inputs are now `x` (was previously `df` in `auto_rate`, `inspect`, `inspect.ft`, and `subsample` among others). Any code using `df =` can be replaced with `x =`. 
 
 - Some functions have had inputs reordered (e.g. `auto_rate` now has `method` as second input). Therefore, code where inputs were not explicitly named may not work as it did previously.  
 
 - Some input defaults have been changed. E.g. in `convert_rate`, `o2.unit = NULL` and `time.unit = NULL` now stop the function instead of applying a default unit.

### Output structural changes

Several functions have had their output object elements renamed to make them consistent. 

 - Data element renamed `$dataframe` instead of `$df`, `$data`, etc. 
 
 - Output rate elements have consistent naming structure starting with `rate`, with a suffix where relevant:
    - `convert_rate` : `output` changed to `rate.output`, `absolute` to `rate.absolute`
    - `calc_rate.bg` : `$bgrate` changed to `$rate.bg`, `$mean` to `$rate.bg.mean`
    - `adjust_rate`  : `corrected` changed to `rate.adjusted`, `input.rate` to `rate.input`

Outputs have also been rearranged, so any referencing not using element names may not work the same (e.g. `output[[2]]`).

Summary tables (`$summary`) now have a `rank` column in position 1, have also in general been rearranged, new columns added, and some columns renamed. Therefore if column numbers or names have been used to extract results these may now be incorrect.

## Function specific changes 

### `import_file()`

This function has been rewritten to be less aggressive about removing empty or non-numeric columns. Now, all columns are retained, where possible. Column renaming has been changed to be more robust, provide unique names, and remove problematic characters. The result is any previous datasets imported using this function will have different column structures and references. Best option is to reimport the data, check the structure, and edit any column references in subsequent code. 

### `format_time()`

If saving output as a data frame, the added numeric time column is now titled `time.num` rather than `elapsed`. If the reference `$elapsed` is used in code for some reason, find and replace `$elapsed` with `$time.num`.

### `auto_rate()`

Primary input `df` now renamed to `x`. Any code using `df =` can be replaced with `x =`.

Inputs have been reordered with `method` as second input. Code where inputs were not explicitly named may not work as it did previously. 

The `"max"` and `"min"` methods have been deprecated. These still work as before for now, so older code using these will still work, but they will be removed in a future version. Most users should use `"highest"` and `"lowest"` instead. Note, new `"maximum"` and `"minimum"` methods **do not** work the same, as they order strictly numerically. See `help(auto_rate)`.

### `convert_DO()`

The `"%"` oxygen unit has been deprecated and replaced with `"%Air"`, and the additional unit of `"%O2"` added. In older code replace `"%"` (and other variations such as `"percent"`) with `"%Air"`. See `help("convert_DO")`.

### `adjust_rate()`

This function has been completely rewritten to incorporate several new adjustment methods. The original inputs (`x` and `by`) have been retained as the first two inputs, and the default behaviour of applying the mean of all background rates in `by` as the adjustment value is also retained. Therefore, older code *should* work as before, but care should be taken that the desired adjustments are applied as expected.

### `calc_rate()`

- `$rate_2pt` element renamed to `$rate.2pt` 
- `$summary` columns renamed and reordered

### `calc_rate()` and `subset_data()`

A change to the code for determining `by = "o2"` ranges to ensure it works with both oxygen production data as well as oxygen uptake data, means that output results may differ from those in v1.1. The previous behaviour was the function found the first occurrence of the `from` value, then the first occurrence of `to`, with rates determined between these bounds. Now, it finds the first occurrence of `from`, then the *last* occurrence of `to`. With most data any difference in rates as a result of this change should be minor. Also as a result, data subsets in `subset_data()` using this method now tend to be longer. 

### `inspect()`

The output `$list` and `$list_raw` elements renamed `locs` and `$locs_raw`. Code should not need to be updated unless these were used to fix data issues in the relevant data frames.


