context("convert.rate")

test_that("output conversions, using %, have expected results", {
  expect_equal(round(convert.rate(10, "%", "mg/l")$output, 3), 0.675)
  expect_equal(round(convert.rate(10, "%", "ug/l")$output, 3), 675.11)
  expect_equal(round(convert.rate(10, "%", "mmol/l")$output, 3), 0.021)
  expect_equal(round(convert.rate(10, "%", "umol/l")$output, 3), 21.098)
  expect_equal(round(convert.rate(10, "%", "ml/l")$output, 3), 0.516)
  expect_equal(round(convert.rate(10, "%", "mg/kg")$output, 3), 0.66)
  expect_equal(round(convert.rate(10, "%", "ug/kg")$output, 3), 659.79)
  expect_equal(round(convert.rate(10, "%", "mmol/kg")$output, 3), 0.021)
  expect_equal(round(convert.rate(10, "%", "umol/kg")$output, 3), 20.619)
  expect_equal(round(convert.rate(10, "%", "ml/kg")$output, 3), 0.504)
  expect_equal(round(convert.rate(10, "%", "%")$output, 3), 10)
  expect_equal(round(convert.rate(10, "%", "hPa")$output, 3), 20.854)
  expect_equal(round(convert.rate(10, "%", "kPa")$output, 3), 2.085)
  expect_equal(round(convert.rate(10, "%", "mmHg")$output, 3), 15.642)
  expect_equal(round(convert.rate(10, "%", "inHg")$output, 3), 0.616)
  expect_equal(round(convert.rate(10, "%", "Torr")$output, 3), 15.642)
})
test_that("conversion works with changing salinity value", {
  expect_equal(round(convert.rate(7.5, "%", "mg/l", S = 35)$output, 3), 0.506)
  expect_equal(round(convert.rate(7.5, "%", "mg/l", S = 25)$output, 3), 0.536)
  expect_equal(round(convert.rate(7.5, "%", "mg/l", S = 15)$output, 3), 0.567)
  expect_equal(round(convert.rate(7.5, "%", "mg/l", S = 5)$output, 3), 0.601)
  expect_equal(round(convert.rate(7.5, "%", "mg/l", S = 0)$output, 3), 0.618)
})
test_that("conversion works with changing pressure value", {
  expect_equal(round(convert.rate(7.5, "%", "mg/l", P = 0.337)$output, 3), 0.168)
})
test_that("conversion works with changing temperature", {
  expect_equal(round(convert.rate(100, "%", "mg/l", t = 25)$output, 3), 6.751)
  expect_equal(round(convert.rate(100, "%", "mg/l", t = 20)$output, 3), 7.377)
})
