<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Determining Pcrit • respR</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Determining Pcrit">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">respR</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">0.0.3</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/respR.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/auto_rate.html">Automatic detection of respirometry parameters</a>
    </li>
    <li>
      <a href="../articles/flowthrough.html">Flowthrough respirometry</a>
    </li>
    <li>
      <a href="../articles/intermittent.html">Analysis of intermittent-flow data</a>
    </li>
    <li>
      <a href="../articles/pcrit.html">Determining Pcrit</a>
    </li>
    <li>
      <a href="../articles/performance.html">Assessing the performance of respR's auto_rate function in detecting linear data</a>
    </li>
    <li>
      <a href="../articles/twopoint.html">Two-point analyses</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/januarharianto/respr">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Determining Pcrit</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/januarharianto/respr/blob/master/vignettes/pcrit.Rmd"><code>vignettes/pcrit.Rmd</code></a></small>
      <div class="hidden name"><code>pcrit.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level3">
<h3 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h3>
<p><span class="math inline">\(P_{crit}\)</span> is the <span class="math inline">\(O_2\)</span> concentration above which oxygen uptake rate is independent of the concentration. In some species - oxyconformers - routine uptake is proportional to oxygen concentration, and so at 50% <span class="math inline">\(O_2\)</span>, the uptake rate will be half that at 100% <span class="math inline">\(O_2\)</span>. Many species however - oxyregulators - are able to regulate uptake, and maintain routine rates as oxygen decreases (although there is a continuum of responses between these extremes, with intermediate cases). The concentration below which routine uptake becomes unsustainable is termed the critical partial pressure of <span class="math inline">\(O_2\)</span>, or simply <span class="math inline">\(P_{crit}\)</span>. It is typically determined in long term, closed respirometry experiments in which the specimen is allowed to deplete the oxygen in the chamber to hypoxia, and identifying the breakpoint in the relationship of uptake rate to <span class="math inline">\(O_2\)</span>.</p>
</div>
<div id="example-data" class="section level3">
<h3 class="hasAnchor">
<a href="#example-data" class="anchor"></a>Example data</h3>
<p>The example data, <code>squid.rd</code>, contains measurements of oxygen consumption in the market squid, <em>Doryteuthis opalescens</em>. Detailed information about the data, including its source and methods, can be obtained with the command <code><a href="../reference/squid.rd.html">?squid.rd</a></code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(respR)
<span class="kw">data</span>(<span class="st">"squid.rd"</span>)
<span class="kw">head</span>(squid.rd)
<span class="co">#&gt;   Time       o2</span>
<span class="co">#&gt; 1    0 7.726446</span>
<span class="co">#&gt; 2    1 7.726446</span>
<span class="co">#&gt; 3    2 7.726446</span>
<span class="co">#&gt; 4    3 7.726446</span>
<span class="co">#&gt; 5    4 7.726446</span>
<span class="co">#&gt; 6    5 7.726446</span></code></pre></div>
<p>This dataset is extremely large; over 34000 rows representing 9.5h of data. The functions in <code>respR</code> are highly optimised and efficient, but users on older machines may want to use the <code>subsample</code> function to thin the dataset before running the following code.</p>
</div>
<div id="inspecting-data" class="section level3">
<h3 class="hasAnchor">
<a href="#inspecting-data" class="anchor"></a>Inspecting data</h3>
<p>We can examine the dataset using the <code>inspect_data</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">market.squid &lt;-<span class="st"> </span><span class="kw"><a href="../reference/inspect_data.html">inspect_data</a></span>(squid.rd)
<span class="co">#&gt; o2 :  num [1:34120] 7.73 7.73 7.73 7.73 7.73 ...</span>
<span class="co">#&gt; Time :  int [1:34120] 0 1 2 3 4 5 6 7 8 9 ...</span>
<span class="co">#&gt; ---</span>
<span class="co">#&gt;                     Score</span>
<span class="co">#&gt; No NA/NaN in time   PASS </span>
<span class="co">#&gt; No NA/NaN in Oxygen PASS </span>
<span class="co">#&gt; Sequential Time     PASS </span>
<span class="co">#&gt; Non-duplicated Time PASS </span>
<span class="co">#&gt; Evenly-spaced Time  PASS</span>
<span class="co">#&gt; New dataframe generated.</span></code></pre></div>
<p><img src="pcrit_files/figure-html/unnamed-chunk-3-1.png" width="576"></p>
<p>We can see from the bottom plot the uptake rate is relatively consistent to around the 10,000th row (this will differ in thinned data), after which it declines steadily, but we do not know from this plot what <span class="math inline">\(O_2\)</span> concentration this represents. For now, we can see the dataset is sound so we can pass the saved <code>market.squid</code> object to the dedicated <span class="math inline">\(P_{crit}\)</span> function.</p>
</div>
<div id="p_crit-function" class="section level3">
<h3 class="hasAnchor">
<a href="#p_crit-function" class="anchor"></a><span class="math inline">\(P_{crit}\)</span> function</h3>
<p>The <code>pcrit</code> function uses two methods to estimate the breakpoint in the rate~<span class="math inline">\(O_2\)</span> relationship. The first is a “broken-stick” regression (BSR) approach, adapted from Yeager &amp; Ultsch (1989) in which two segments of the data are iteratively fitted and the intersection with the smallest sum of the residual sum of squares between the two linear models is the estimated critical point. The second is a wrapper for the segmented, or “broken-line” regression approach, available as part of the <code>segmented</code> R package (Muggeo 2008), which estimates the critical point by iteratively fitting two intersecting models and selecting the point that minimises the “gap” between the fitted lines (see <code><a href="../reference/pcrit.html">?pcrit</a></code> for full citations).</p>
<p>We will pass the data frame contained in <code>market.squid</code> to <code>pcrit</code> with the default operators:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">market.squid.pcrit &lt;-<span class="st"> </span><span class="kw"><a href="../reference/pcrit.html">pcrit</a></span>(market.squid<span class="op">$</span>df)</code></pre></div>
<pre><code>#&gt; Performing broken-stick analysis...
#&gt; Performing segmented (breakpoint) analysis...
#&gt; Convergence attained in 2 iterations.</code></pre>
<p><img src="pcrit_files/figure-html/unnamed-chunk-5-1.png" width="576"></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(market.squid.pcrit)</code></pre></div>
<pre><code>#&gt; --Broken stick (Yeager &amp; Ultsch 1989)--
#&gt; Sum RSS     1.2689e-07
#&gt; Intercept   2.60922
#&gt; Midpoint    2.60805
#&gt; 
#&gt; --Segmented (Muggeo 2003)--
#&gt; Std. Err.   0.00998917
#&gt; Breakpoint  2.62006</code></pre>
<p>The output figure shows both methods and their metrics plotted against the original data and on a rate~<span class="math inline">\(O_2\)</span> plot. The <code>print</code> summary shows that, in this case, both methods give very similar values for the <span class="math inline">\(P_{crit}\)</span>: 2.61 and 2.62 mg/L. We should note that for some data, depending on various characteristics, such as noisyness, abruptness of the break, etc. the two methods may provide results that differ. The plots will allow the user to judge which method works better at identifying the ‘true’ <span class="math inline">\(P_{crit}\)</span> value. We should also note the <code>width</code> operator, which controls the width of the rolling regressions used to calculate the rolling rate values, will also affect estimations of the <span class="math inline">\(P_{crit}\)</span>. The default value of 0.1 of the total length of data in our testing seems to provide good results, but in some data changing this may give better results.</p>
<p>Also important to note is that the segmented (Muggeo) method sometimes gives a different result when the exact same code is run. See the documentation for the <code>segmented</code> package and publications by Muggeo for the details of why this is, but briefly, it comes from a randomisation of the starting point for the initial analysis. The differences introduced by this are usually minor.</p>
<p>This example used raw Time~<span class="math inline">\(O_2\)</span> data, and so the function calculated a rolling rate internally. However, the user can input already calculated rate~<span class="math inline">\(O_2\)</span> data using the argument <code>has.rate = TRUE</code>, and the function will determine Pcrit using these data directly. These data can be either whole specimen rates (“<span class="math inline">\(VO_2\)</span>”), or mass-specific rates (“<span class="math inline">\(MO_2\)</span>”); both give identical results.</p>
<p>The <code>pcrit</code> function also includes a default <code>parallel = TRUE</code> argument. This instructs the function to use paralell processing to speed up the analysis, if your system supports it. In the case of any o errors or problems using the function, changing this to <code>FALSE</code> is a good first step in diagnosing the problem.</p>
</div>
<div id="adjustments" class="section level3">
<h3 class="hasAnchor">
<a href="#adjustments" class="anchor"></a>Adjustments</h3>
<p>The <code>pcrit</code> function does not support adjusting rates for background effects. Background <span class="math inline">\(O_2\)</span> uptake should not affect <span class="math inline">\(P_{crit}\)</span> as it is typically assumed to be uniform over the course of an experiment. Users should be aware that rates extracted from objects of class <code>pcrit</code> will not have been background-corrected.</p>
</div>
<div id="extracting-results" class="section level3">
<h3 class="hasAnchor">
<a href="#extracting-results" class="anchor"></a>Extracting results</h3>
<p>Results of <code>pcrit</code> analyses can be extracted from the results object via the following:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Broken-stick regression (Yeager &amp; Ultsch, 1989)</span>
market.squid.pcrit<span class="op">$</span>result.intercept
<span class="co">#&gt; [1] 2.609219</span>

<span class="co"># Segmented regression (Muggeo 2003).</span>
market.squid.pcrit<span class="op">$</span>result.segmented
<span class="co">#&gt; [1] 2.620064</span></code></pre></div>
<p>We can also export the results into a .csv file using the <code>summary()</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(market.squid.pcrit)
<span class="co">#&gt; Top Result for all Methods:</span>
<span class="co">#&gt;    splitpoint       sumRSS pcrit.intercept pcrit.mpoint pcrit.segmented</span>
<span class="co">#&gt; 1:    2.60432 1.268899e-07        2.609219      2.60805        2.620064</span>

<span class="co"># Uncomment to run</span>

<span class="co"># write.csv(summary(market.squid.pcrit), 'results.csv')</span></code></pre></div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Januar Harianto, Nicholas Carey.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  

  </body>
</html>
