# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install required packages
        run: |
          Rscript -e 'install.packages(c("covr", "lubridate", "marelac", "purrr", "roll", "segmented", "xml2"))'

      - name: Install archived dependencies
        run: |
          # Install any dependencies these packages might need first
          Rscript -e 'install.packages(c("tcltk2", "signal", "XML", "chron", "data.table", "dplyr", "ggplot2", "gridExtra", "RCurl", "reshape2", "stringr"))'
          # Install archived packages
          Rscript -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/rMR/rMR_1.0.5.tar.gz", repos = NULL, type = "source")'
          Rscript -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/FishResp/FishResp_1.1.0.tar.gz", repos = NULL, type = "source")'

      - name: Install package
        run: |
          Rscript -e 'install.packages(".", repos = NULL, type = "source")'

      - name: Test coverage
        run: |
          Rscript -e 'library(covr); codecov(quiet = FALSE)'
